CustomRoleBasedAuthenticationInASPNetMVC/Controllers/ActionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CRBA.DataAccessLayer;
using CRBA.Models;

namespace CustomRoleBasedAuthenticationInASPNetMVC.Controllers
{
    public class ActionController : Controller
    {
        private readonly UserDbContext _dbContext = new UserDbContext();

        // GET: SActions
        public async Task<ActionResult> ControllerActionList()
        {
            List<ControllerAction> actionList = await _dbContext.ControllerActions.Include(s => s.ActionCategory).ToListAsync();
            return View(actionList);
        }

        // GET: SActions/Details/5
        public async Task<ActionResult> ControllerActionDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ControllerAction controllerAction = await _dbContext.ControllerActions.FindAsync(id);
            if (controllerAction == null)
            {
                return HttpNotFound();
            }
            return View(controllerAction);
        }

        private async Task PopulateActionCategoryDropDownList(int? selectedActionCategory = null)
        {
            List<ActionCategory> actionCategories = await _dbContext.ActionCategories.ToListAsync();
            ViewBag.ActionCategoryId = new SelectList(actionCategories, "ActionCategoryId", "ActionCategoryName",selectedActionCategory);
        }
        // GET: SActions/Create
        public async Task<ActionResult> CreateControllerAction()
        {
            await PopulateActionCategoryDropDownList();
            return View();
        }

        // POST: SActions/Create
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateControllerAction([Bind(Include = "ActionCategoryId,ActionName,Description")] ControllerAction controllerAction)
        {
            if (ModelState.IsValid)
            {
                _dbContext.ControllerActions.Add(controllerAction);
                await _dbContext.SaveChangesAsync();
                return RedirectToAction("ControllerActionList");
            }

            await PopulateActionCategoryDropDownList(controllerAction.ActionCategoryId);
            return View(controllerAction);
        }

        // GET: SActions/Edit/5
        public async Task<ActionResult> UpdateControllerAction(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ControllerAction controllerActionToBeUpdated = await _dbContext.ControllerActions.FindAsync(id);
            if (controllerActionToBeUpdated == null)
            {
                return HttpNotFound();
            }
            await PopulateActionCategoryDropDownList(controllerActionToBeUpdated.ActionCategoryId);
            return View(controllerActionToBeUpdated);
        }

        // POST: SActions/Edit/5
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> UpdateControllerAction(int id,ControllerAction controllerAction)
        {
            if (ModelState.IsValid)
            {
                ControllerAction controllerActionToBeUpdated = await _dbContext.ControllerActions.FindAsync(id);
                if (TryUpdateModel(controllerActionToBeUpdated,"", new []{ "ActionCategoryId", "ActionName", "Description" }))
                {
                    await _dbContext.SaveChangesAsync();
                }
                
                return RedirectToAction("ControllerActionList");
            }
            await PopulateActionCategoryDropDownList(controllerAction.ActionCategoryId);
            return View(controllerAction);
        }

        // GET: SActions/Delete/5
        public async Task<ActionResult> DeleteControllerAction(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ControllerAction controllerActionToBeDeleted = await _dbContext.ControllerActions.FindAsync(id);
            if (controllerActionToBeDeleted == null)
            {
                return HttpNotFound();
            }
            return View(controllerActionToBeDeleted);
        }

        // POST: SActions/Delete/5
        [HttpPost, ActionName("DeleteControllerAction")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteControllerActionConfirmed(int id)
        {
            ControllerAction controllerActionToBeDeleted = await _dbContext.ControllerActions.FindAsync(id);
            if (controllerActionToBeDeleted != null)
            {
                _dbContext.ControllerActions.Remove(controllerActionToBeDeleted);
                await _dbContext.SaveChangesAsync();
            }
            return RedirectToAction("ControllerActionList");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _dbContext.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CustomRoleBasedAuthenticationInASPNetMVC/Controllers/SecurityController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using CRBA.ServiceLayer;
using CRBA.DataAccessLayer;
using CRBA.Models;

namespace CustomRoleBasedAuthenticationInASPNetMVC.Controllers
{
    public class SecurityController : Controller
    {
        private readonly UserDbContext _dbContext = new UserDbContext();

        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> UpdateControllerAndActionNames()
        {
            List<string> newControllerNames = GetAllControllerAndActionNames.GetControllerNames2();
            HashSet<string> newControllerNamesHs = new HashSet<string>(newControllerNames);

            List<string> existingControllerNames =  await _dbContext.ActionCategories.AsNoTracking().Select(x => x.ActionCategoryName).ToListAsync();
            HashSet<string> existingControllerNamesHs = new HashSet<string>(existingControllerNames);

            List<string> controllerNamesToBeDeleted = existingControllerNamesHs.Except(newControllerNamesHs).ToList();

            foreach (string controllerName in controllerNamesToBeDeleted)
            {
                ActionCategory controllerToBeDeleted = await _dbContext.ActionCategories.FirstOrDefaultAsync(x => x.ActionCategoryName == controllerName);
                if (controllerToBeDeleted != null)
                {
                    _dbContext.ActionCategories.Remove(controllerToBeDeleted);
                }
                
            }


            foreach (string controllerName in newControllerNamesHs)
            {
                string [] ingnoreControllerNameArray = new [] {"Validation", "ActionCategory", "Action"};
                if (ingnoreControllerNameArray.Contains(controllerName, StringComparer.CurrentCultureIgnoreCase))
                {
                    continue;
                }

                ActionCategory existingActionCategory = await _dbContext.ActionCategories.FirstOrDefaultAsync(x => x.ActionCategoryName == controllerName);

                List<string> newActionNames = GetAllControllerAndActionNames.GetActionNamesByController(controllerName);
                HashSet<string> newActionNamesHs = new HashSet<string>(newActionNames);

                
                if (existingActionCategory == null)
                {
                    ActionCategory actionCategory = new ActionCategory
                    {
                        ActionCategoryName = controllerName,
                        Description = "This is a Controller"
                    };

                    foreach (string actionName in newActionNamesHs)
                    {
                            ControllerAction controllerAction = new ControllerAction()
                            {
                                ActionCategoryId = actionCategory.ActionCategoryId,
                                ActionName = actionName,
                                Description = "This is an action of " + controllerName + " Controller"
                            };
                        actionCategory.ControllerActions.Add(controllerAction);
                    }

                    _dbContext.ActionCategories.Add(actionCategory);

                }
                else
                {
                    List<string> existingtActionNames = existingActionCategory.ControllerActions.Select(x => x.ActionName).ToList();
                    HashSet<string> existingtActionNamesHs = new HashSet<string>(existingtActionNames);

                    List<string> actionNamesToBeDeleted = existingtActionNamesHs.Except(newActionNamesHs).ToList();

                    foreach (string actionName in actionNamesToBeDeleted)
                    {
                        ControllerAction controlleActionToBeDeleted = _dbContext.ControllerActions.FirstOrDefault(x => x.ActionCategoryId == existingActionCategory.ActionCategoryId && x.ActionName == actionName);
                        if (controlleActionToBeDeleted != null)
                        {
                            _dbContext.ControllerActions.Remove(controlleActionToBeDeleted);
                        }
                        
                    }

                    List<string> actionNamesToBeAdded = newActionNamesHs.Except(existingtActionNamesHs).ToList();

                    foreach (string actionName in actionNamesToBeAdded)
                    {
                        ControllerAction controllerAction = new ControllerAction()
                        {
                            ActionCategoryId = existingActionCategory.ActionCategoryId,
                            ActionName = actionName,
                            Description = "This is an action of " + controllerName + " Controller"
                        };
                        _dbContext.ControllerActions.Add(controllerAction);
                    }
                }
                
            }

           _dbContext.SaveChanges();

            return View();
        }
    }
}

CustomRoleBasedAuthenticationInASPNetMVC/Views/Action/ControllerActionDetails.cshtml
@model CRBA.Models.ControllerAction

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>SAction</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ActionCategory.ActionCategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActionCategory.ActionCategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ActionName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActionName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ActionId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CustomRoleBasedAuthenticationInASPNetMVC/Views/Action/ControllerActionList.cshtml
@model IEnumerable<CRBA.Models.ControllerAction>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ActionCategory.ActionCategoryName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ActionName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>Actions</th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ActionCategory.ActionCategoryName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ActionName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.ActionLink("Edit", "UpdateControllerAction", new { id=item.ControllerActionId }) |
                @Html.ActionLink("Details", "ControllerActionDetails", new { id=item.ControllerActionId }) |
                @Html.ActionLink("Delete", "DeleteControllerAction", new { id=item.ControllerActionId })
            </td>
        </tr>
    }

</table>
<div class="text-center">
    <a class="btn btn-primary" href="@Url.Action("Index","Security")">Back to Security</a>
</div>

CustomRoleBasedAuthenticationInASPNetMVC/Views/Action/CreateControllerAction.cshtml
@model CRBA.Models.ControllerAction

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SAction</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ActionCategoryId, "ActionCategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ActionCategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ActionCategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ActionName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ActionName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ActionName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CustomRoleBasedAuthenticationInASPNetMVC/Views/Action/DeleteControllerAction.cshtml
@model CRBA.Models.ControllerAction

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SAction</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ActionCategory.ActionCategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActionCategory.ActionCategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ActionName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActionName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CustomRoleBasedAuthenticationInASPNetMVC/Views/Action/UpdateControllerAction.cshtml
@model CRBA.Models.ControllerAction

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SAction</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ActionId)

        <div class="form-group">
            @Html.LabelFor(model => model.ActionCategoryId, "Action Category", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ActionCategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ActionCategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ActionName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ActionName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ActionName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}